---
title: "Dashboard"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rvest)
```

```{r loading dataset}
data(rest_inspec)

rest_inspec = 
  rest_inspec %>% 
  filter(
    boro %in% c("MANHATTAN", "BROOKLYN", "QUEENS"),
    grade %in% c("A", "B", "C"),
    cuisine_description %in% c("American", "French", "Italian", "Mexican", "Pakistani", "Korean", "Middle Eastern", "Russian", "Thai", "Turkish", "Indian", "Indonesian", "Japanese", "Chinese", "Ethiopian"), 
    critical_flag != "Not Applicable"
    ) %>% 
  select(  
    boro, score, cuisine_description, critical_flag, grade, inspection_type, grade_date) %>% 
  na.omit()
```

```{r}
rest_inspec %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, -n)) %>% 
  plot_ly(
    x = ~cuisine_description, y = ~n, type = "bar", colors = ~"magma", color = ~cuisine_description) 
```

```{r}
rest_inspec %>% 
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, -n)) %>% 
  plot_ly(
    x = ~grade, y = ~n, type = "bar", colors = ~"magma", color = ~grade) 
```

```{r}
rest_inspec %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, -n)) %>% 
  plot_ly(
    x = ~boro, y = ~n, type = "bar", colors = ~"magma", color = ~boro) 
```


```{r}
rest_inspec %>% 
  group_by(grade_date, grade) %>% 
  summarize(n_obs = n()) %>% 
  plot_ly(
  y = ~n_obs,
  x = ~grade_date,
  color = ~grade,
  type = "scatter",
  colors = "magma", 
  mode = "lines",
  fill = "tozeroy")

```

