---
title: "Dasboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    souce: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rvest)
```


```{r loading dataset}
data(rest_inspec)

rest_inspec = 
  rest_inspec %>% 
  filter(
    boro %in% c("MANHATTAN", "BROOKLYN", "QUEENS"),
    grade %in% c("A", "B", "C"),
    cuisine_description %in% c("American", "French", "Italian", "Mexican", "Pakistani", "Korean", "Middle Eastern", "Russian", "Thai", "Turkish", "Indian", "Indonesian", "Japanese", "Chinese", "Ethiopian"), 
    critical_flag != "Not Applicable"
    ) %>% 
  select(  
    boro, score, cuisine_description, critical_flag, grade, inspection_type, grade_date) %>% 
  na.omit()
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, -n)) %>% 
  plot_ly(
    x = ~cuisine_description, 
    y = ~n, type = "bar", 
    colors = ~"magma", 
    color = ~cuisine_description) 
```

### Chart B

```{r}
rest_inspec %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(
    y = ~score, 
    color = ~boro,
    type = "box", 
    colors = "magma")
```


### Chart C

```{r}
rest_inspec %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, -n)) %>% 
  plot_ly(
    x = ~boro, 
    y = ~n, 
    type = "bar", 
    colors = ~"magma", 
    color = ~boro) 
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart D

```{r}
rest_inspec %>% 
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, -n)) %>% 
  plot_ly(
    x = ~grade, 
    y = ~n, 
    type = "bar", 
    colors = ~"magma", 
    color = ~grade) 
```

#### Chart E

```{r}
boro_trend = 
  rest_inspec %>% 
  group_by(boro, grade, grade_date) %>% 
  summarize(n_obs = n()) %>% 
  ggplot(aes(y = n_obs, x = grade_date, color = grade)) + 
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_color_brewer(palette = "RdPu") +
  facet_grid(~boro) +
  xlab("\n \n \n Grade Date") + ylab("Number of Observations \n \n")

ggplotly(boro_trend)
```