---
title: ""
output: html_document
---

### Current Courses
#### Columbia University Mailman School of Public Health
##### Graduate Teaching Assistant 
Fall 2020 <br>
Globalization and Developmental Perspectives <br>

- __Dates:__ June 2020 – Present
- __Location:__ New York, NY, US
- __Description:__
Provide technological support for the studio "Global and Developmental Perspectives" to develop online course content on [Rise 360](https://rise.com/rise-built-by-articulate?utm_source=google&utm_medium=cpc&utm_campaign=rise&gclid=CjwKCAiAv4n9BRA9EiwA30WND1Kb4xt2WynrWmkBF1vkDR_k1g04GJiU1ScK31zaDQ08wnJ-u5mNTRoCKVkQAvD_BwE), an online teaching tool. Additionally, I provide academic support to 50 graduate students, including holding weekly office hours and grade assignments on Learning Management Systems (Courseworks/Canvas). <br><br>


### Past Courses
#### Lahore University of Management Sciences
##### Teaching Assistant 
Spring 2019 <br>
Introductory Biology <br>

- __Dates:__ January 2019 – May 2019
- __Location:__ Lahore, Pakistan
- __Description:__ 
Provided academic support to 30 first-year undergraduate students through weekly office hours and tutorials. <br>

Spring 2017 <br>
Introductory Biology <br>

- __Dates:__ January 2017 – May 2017
- __Location:__ Lahore, Pakistan
- __Description:__ 
Provided academic support to 30 first-year undergraduate students through weekly office hours and tutorials. <br>